### ISSUE TITLE
Implement cron-style, recurring tasks

### ISSUE THREAD

**Issue by rosa** [basecamp/solid_queue#104]
A dispatcher would handle these, and the configuration will be included in `solid_queue.yml`.

**Comment by rmontgomery429** [comment]
I am excited about this project and would love to contribute. Before I get to far down the wrong path, I'd like to clarify a few aspects to ensure alignment with the project's vision.

**Proposed Format for Cron-like Tasks:**

I suggest the following YAML structure for defining recurring tasks:

```yaml
recurring_tasks:
  - task: "DailyReport.generate"
    schedule: "every day at noon"
  - task: "DatabaseCleanup.run"
    schedule: "every 10 minutes"
  - task: "SendBroadcast.start"
    schedule: "0 4 * * 0"
```

This format aims to provide flexibility in scheduling any arbitrary class method. It supports both a human-readable syntax and traditional cron syntax for broader flexibility.

**Questions for Clarification:** Dependency on Fugit: Is the project open to depending on external gems like Fugit for parsing the cron syntax? Or is there a preference for a simpler, in-house solution to avoid additional dependencies?

**Task Execution Mechanism:** Are there any specific considerations or constraints regarding how these tasks should be executed within the project's existing architecture? It seems like spinning the idea would be to spin up a dispatcher for each scheduled task but maybe you have already thought through this and another suggestion.

Your guidance on these points will help ensure that my contributions align well with the project's roadmap and existing design principles.

Looking forward to your feedback and excited to contribute to this feature.

**Comment by ianterrell** [comment]
Just 2¢ as a user of GoodJob looking to migrate to SolidQueue when the time comes, I really like GoodJob's cron-style support: https://github.com/bensheldon/good_job#cron-style-repeatingrecurring-jobs

I most like:
- it only schedules jobs, not arbitrary code (e.g. `class: "DailyReportJob"` not `task: "DailyReport.run"`)
- it allows setting args/kwargs for the jobs (due to above)
- setting priority

I mainly like that it feels like a lower mental overhead in that only jobs get scheduled. 

But there are arguably some objective measurements around that, like I can customize my `retry_on` and concurrency controls for scheduled jobs using the same mechanisms as any other job, etc, since they're all plain jobs.

**Comment by rmontgomery429** [comment]
I've been giving this more thought and realized there's another snag with the class method approach. Imagine if someone calls a method that unexpectedly bogs down the system or even grinds it to a halt. I think it's important that the scheduler-dispatcher only backgrounds jobs, and being able to call a class method wouldn't allow it to know if it's safe to call. So...

**Thinking of a Fix:**

Maybe the key is to simplify things. How about we put some constraints in place? Like, the scheduler could always fire off a job with no arguments, as in `DailyReport.perform_later`. This way, we're only queuing jobs at the scheduled times without the complexities of additional arguments or the risk of lengthy class method executions.

```yaml
recurring_tasks:
  - job: "DailyReport"
    schedule: "every day at noon"
```

In this scenario, the scheduler automatically calls `DailyReport.perform_later`, keeping it neat and safe.

**But Here's the Catch:**

This solution definitely makes things safer and simpler. But I'm wondering, are we straying from the original goal of this feature? Is this sacrificing too much flexibility for the sake of simplicity and safety?

**Comment by ianterrell** [comment]
Thanks for your careful thought on this. A few notes that come to mind.

> **Testability** ... My idea of using class methods like DailyReport.generate would add a layer where we can easily see and _test_ what's happening.

I am probably misunderstanding what you mean, but I think job testability is excellent in Rails already and I'm not sure what adding a layer on top would bring to that.

> the scheduler could always fire off a job with no arguments

The use case I have for arguments is in re-use of jobs. Consider:

```yaml
recurring_tasks
  - job: ReportEmailer
    kwargs:
      report: daily-usage
      to: me@company.com
    schedule: "every day at 8am"
  - job: ReportEmailer
    kwargs:
      report: weekly-usage
      to: 
        - me@company.com
        - myboss@company.com
    schedule: "every Monday at 8am"
```

We do this both within applications for some jobs that are very similar and just need parameterized across schedulings, as well as with library code that is written and just needs slightly customized per application.

The args and kwargs are all purely optional. There's no additional mental overhead if you write jobs that do not need parameterized. Personally I think this hits safe, simple, and flexible.

Thanks again for considering the issue!

**Comment by rmontgomery429** [comment]
Thanks for your feedback and for bringing up some really valid points. Let me address them:

**On Testability:**

You're right that job testability in Rails is already top-notch. My thought with adding a class method layer, like `DailyReport.generate`, was more about centralizing and possibly adding custom logic before the job gets queued. It’s less about testing the job itself and more about testing the custom logic that decides when and how a job is queued. But I see your point — if we're mostly queuing straightforward jobs, this extra layer might be overkill.

**Regarding Arguments and Keyword Arguments:**

Your use case for reusing jobs with different parameters makes a lot of sense. Being able to specify arguments or kwargs in the config does add a lot of flexibility, allowing the same job to be tailored for different scenarios. That's a nice feature and it would be really handy to see the jobs like that in one place.

**Striking a Balance:**

I think my initial reaction was to the cron configuration example in the GoodJob docs. It struck me as maybe a little _too_ feature rich. Seeing procs and lambdas alongside both and args and kwargs in a yaml file struck me as a bit of a foot-gun.

Perhaps we can have a system that defaults to queuing jobs without arguments for straightforward tasks, while still offering the ability to specify args/kwargs for more complex scheduling needs.

```yaml
recurring_tasks:
  - job: SimpleJob
    schedule: every day at 9am
  - job: ReportEmailerJob
    kwargs:
      report: daily-usage
      to: me@company.com
    schedule: every day at 8am
  - job: ReportEmailerJob
    kwargs:
      report: weekly-usage
      to: 
        - me@company.com
        - myboss@company.com
    schedule: every Monday at 8am
```
