### ISSUE TITLE
ActiveStorage::AnalyzeJob jobs not running

### ISSUE THREAD

**Issue by olimart** [basecamp/solid_queue#167]
Hey,

I've got some `ActiveStorage::AnalyzeJob` jobs not running (in development, haven't checked other envs).
They're enqueued to the `default` queue (automatically by ActiveStorage).

![Capture d’écran, le 2024-03-07 à 15 19 09](https://github.com/basecamp/solid_queue/assets/547754/ff15f131-44d8-4a2e-b876-79a10d16fe49)

However, other `ActiveJob` jobs are also enqueued to the `default` queue but are processed as expected.
Since other jobs going through the default queue are processed, `ActiveStorage::AnalyzeJob` should run as well, right?

![Capture d’écran, le 2024-03-07 à 15 19 18](https://github.com/basecamp/solid_queue/assets/547754/3cbab47d-29c8-47f5-80c6-8fb4773a23f8)

This is how I start jobs `jobs: bundle exec rake solid_queue:start`
config file

```yml
default: &default
  workers:
    - queues: "critical"
      threads: 10
    - queues: "mailers"
      threads: 5
    - queues: "default"
      threads: 2
    - queues: ["low", "*"]
      threads: 1

development:
  <<: *default
  dispatchers:
    - polling_interval: 5 # default is 1
  workers:
    - polling_interval: 1 # default is 0.1

test:
  <<: *default

production:
  <<: *default
```

**Comment by rosa** [comment]
Hey @olimart! Yes, they should run just in the same way if they are in the `default` queue. However, in your screenshot I see they are indeed running, your first screenshot shows the job in progress, which means it has been picked up by a Solid Queue worker that's running it. It seems the job is hanging for some reason 🤔  To debug it, perhaps you could try to run what the job does manually in your console, as:
```ruby
ActiveStorage::Blob.find(5).analyze
```
and see if that gives you a clue. It doesn't seem like a Solid Queue problem from what I gather, though.

**Comment by arbythree** [comment]
Same problem here. ActiveStorage::Blob.find(NN).analyze runs without incident.

**Comment by olimart** [comment]
Thanks Rosa. Will take another look but `ActiveStorage::Blob.find(5).analyze` runs fine.
What could happen if, like you mentioned, it is in progress (picked up by Solid Queue) but hanging?

**Comment by rosa** [comment]
Hmm... Could you copy your `database.yml` configuration?

**Comment by olimart** [comment]
> Hmm... Could you copy your `database.yml` configuration?

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
```

Along with Puma `threads_count = ENV.fetch("RAILS_MAX_THREADS") { 3 }`
