### ISSUE TITLE
Comma separated queue names don't work

### ISSUE THREAD

**Issue by morgoth** [basecamp/solid_queue#67]
When specifying multiple queues as one string, ie:
```yaml
development:
  workers:
    - queues: real_time,background
```
this does not work. The workers are not taking scheduled jobs (real_time or background) at all.

It works for me, when queues are an array, ie:
```yaml
development:
  workers:
    - queues:
      - real_time
      - background
```

Should the documentation be fixed to list queues as array in YAML or maybe the logic to fix comma separated string?
